### ISSUE TITLE
Document administration endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/api-docs#45]
// Administration Endpoints
app.get('/admin', requireAdmin, views.admin.status)
app.get('/admin/graphs', requireAdmin, views.admin.graphs)
app.get('/admin/log', requireAdmin, views.admin.log)

app.get('/admin/mail', requireAdmin, views.admin.mail)
app.post('/admin/mail', requireAdmin, bodyParser.urlencoded({ extended: true }), views.admin.mail)

app.get('/admin/plugins', requireAdmin, views.admin.plugins)
app.post('/admin/savePlugin', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.savePlugin)
app.post('/admin/deletePlugin', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.deletePlugin)

app.get('/admin/registries', requireAdmin, views.admin.registries)
app.post('/admin/saveRegistry', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.saveRegistry)
app.post('/admin/deleteRegistry', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.deleteRegistry)
app.post('/admin/setAdministratorEmail', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.setAdministratorEmail)
app.post('/admin/retrieveFromWebOfRegistries', requireAdmin, actions.admin.retrieve)
app.post('/admin/federate', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.federate)

app.get('/admin/remotes', requireAdmin, views.admin.remotes)
app.post('/admin/saveRemote', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.saveRemote)
app.post('/admin/deleteRemote', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.deleteRemote)

app.get('/admin/explorer', requireAdmin, views.admin.explorer)
app.post('/admin/explorer', requireAdmin, bodyParser.urlencoded({ extended: true }), views.admin.explorer)
app.post('/admin/explorerUpdateIndex', requireAdmin, actions.admin.explorerUpdateIndex)
app.all('/admin/explorerLog', requireAdmin, actions.admin.explorerLog)

app.get('/admin/theme', requireAdmin, views.admin.theme)
app.post('/admin/theme', requireAdmin, uploadToMemory.single('logo'), views.admin.theme)

app.get('/admin/users', requireAdmin, views.admin.users)
app.post('/admin/users', requireAdmin, views.admin.users)
app.get('/admin/newUser', requireAdmin, views.admin.newUser)
app.post('/admin/newUser', requireAdmin, bodyParser.urlencoded({ extended: true }), views.admin.newUser)
app.post('/admin/updateUser', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.updateUser)
app.post('/admin/deleteUser', requireAdmin, bodyParser.urlencoded({ extended: true }), actions.admin.deleteUser)

**Comment by jvscholz** [comment]
how do I try  /admin/retrieveFromWebOfRegistries?

do we have a webofregistries that I can mess around with?

@cjmyers

**Comment by cjmyers** [comment]
Looks good, but should make clear what <URI> is in each case:

Add member with the specified <URI> to a collection.

Remove member of a collection with the specified <URI>.

**Comment by cjmyers** [comment]
https://wor.synbiohub.org is the public Web-of-Registries.  The POST request is very simple, since it has no parameters.  I'm not sure why it is not a GET request actually.  Anyway, you simply can login, and then you run the POST request, and your instance should get updated.  If I were to build a test, I would delete some of the registries that you should have from WOR (such as maybe synbiohub.org) and then retreive and see if it comes back.

**Comment by jvscholz** [comment]
updated @cjmyers please take a look 

https://synbiohub.github.io/api-docs/#administration-endpoints

**Comment by cjmyers** [comment]
Looks good.  Closing.
