### ISSUE TITLE
Add user endpoints to the documentation

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/api-docs#47]
// User Endpoints
  if (config.get('allowPublicSignup')) {
    app.all('/register', views.register)
  }
  app.all('/login', views.login)
  app.all('/logout', views.logout)
  app.all('/resetPassword/token/:token', actions.resetPassword)
  app.all('/resetPassword', views.resetPassword)
  app.post('/setNewPassword', actions.setNewPassword)
  app.all('/profile', requireUser, views.profile)

**Comment by cjmyers** [comment]
Do not document for API this one:

 app.all('/resetPassword/token/:token', actions.resetPassword)

**Comment by cjmyers** [comment]
Profile has GET and POST

register/login/logout/resetPassword/setNewPassword POST

**Comment by jvscholz** [comment]
updated, take a look? @cjmyers

**Comment by cjmyers** [comment]
Looks good.  A few minor things:

1) Affilation of the user -> Affiliation of the user <-- under register / update profile
2) Register python/javascript need to be generalized
3) View profile would be good to have idea of returned JSON result fields
4) With View and Update profile, should likely mention that an X-authorization token is required for these

**Comment by jvscholz** [comment]
ok, updated
