### ISSUE TITLE
Document add addToCollection and removeMembership

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/api-docs#48]
This two new POST endpoints enable the ability to add an object as a new member of a Collection and to remove a member of a Collection.

**Comment by jvscholz** [comment]
what category of endpoint do these fall under?

**Comment by jvscholz** [comment]
^ edit endpoints

**Comment by cjmyers** [comment]
edit endpoints

**Comment by jvscholz** [comment]
how do I access this feature on synbiohub?

**Comment by cjmyers** [comment]
The easiest process is to create an empty Collection using the Submit process.  Then browse to some public part and click on the "chain link" and add it to your new Collection.  Then, when you go to the Collection, you can click on the "unlink" button to remove it from the Collection.

**Comment by jvscholz** [comment]
ok, it's been updated @cjmyers

**Comment by cjmyers** [comment]
Looks good, but should make clear what is in each case:

Add member with the specified to a collection.

Remove member of a collection with the specified .
