### ISSUE TITLE
Add reference to the SBH paper in the documentation

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/api-docs#52]
Please add a reference to the SBH paper in the About section, the SBH Plugin paper in the Plugin section, and the SBOLExplorer paper when it is first mentioned:

https://pubs.acs.org/doi/abs/10.1021/acssynbio.7b00403 (SBH Paper)

https://pubs.acs.org/doi/abs/10.1021/acssynbio.0c00056 (SBH Plugin Paper)

https://pubs.acs.org/doi/abs/10.1021/acssynbio.9b00089 (SBOLExplorer)

**Comment by jvscholz** [comment]
updated
