### ISSUE TITLE
Improve search python example

### ISSUE THREAD

**Issue by tcmitchell** [SynBioHub/api-docs#59]
The Python example for "Search metadata" does not provide enough information to be useful. For instance, it does not explain how to quote the arguments, nor does it explain that URIs must be wrapped in '<' and '>'. Here is a complete, runnable example which mimics the query listed in the JavaScript example:

```python
import urllib.parse
import requests

search_url = 'https://synbiohub.org/search'
# Coding Sequence
SO_CDS = 'http://identifiers.org/so/SO:0000316'

query_terms = {'objectType': 'ComponentDefinition',
               'role': f'<{SO_CDS}>'}
query = urllib.parse.urlencode(query_terms)
search_text = 'GFP'
param_terms = {'offset': 0, 'limit': 10}
params = urllib.parse.urlencode(param_terms)

url = f'{search_url}/{query}&{search_text}/?{params}'
response = requests.get(url, headers={'Accept': 'text/plain'})

print(response.status_code)
if response:
    records = response.json()
    for record in records:
        print(f'{record["name"]}: {record["description"]}')
```

**Comment by jvscholz** [comment]
Hey, I've revised the documentation of the variables to reflect the true URI input. That being said, I'll limit the changes thereto maintain its size and conciseness.
