### ISSUE TITLE
Update edit field endpoints

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/api-docs#64]
The edit field endpoints have a few more possibilities:

remove field - title, description, wasDerivedFrom, annotation
add field - wasDerivedFrom, annotation
edit field - annotation

To support annotation, there is now a "pred" parameter for the predicate for the annotation, which should be provided for all remove, add, or edit when working with an annotation.

**Comment by jvscholz** [comment]
updated

**Comment by cjmyers** [comment]
Let's change pred to:

A predicate for an annotation.

You can drop the only valid for, since it is likely obvious from the definition.

**Comment by jvscholz** [comment]
updated

**Comment by cjmyers** [comment]
Looks good.  Closing.
